### ISSUE TITLE
import ImageView hangs after import PyPlot

### ISSUE THREAD

**Issue by CCWRoy** [JuliaImages/ImageView.jl#128]
Hello, I'm having some issues with PyPlot and ImageView.

1) If I `import PyPlot` before `import ImageView`, the Julia REPL hangs after a few seconds. 
2) If I `import ImageView` before `import PyPlot`, I get an error saying PyPlot cannot find matplotlib in my selected Python distribution. 
3) I can run PyPlot functions just fine from a fresh REPL session.

I'm on Ubuntu 16.04.3 64-bit, using Julia 0.6 generic linux binaries. ImageView is 0.6.0, PyPlot is 2.3.2, PyCall is 1.15.0. The Python 3 distribution that I'm linked to is Anaconda 4.4.0. I can provide more info if you cannot reproduce this error.

**Comment by timholy** [comment]
Maybe https://github.com/JuliaGraphics/Gtk.jl/issues/193?

**Comment by timholy** [comment]
(For what it's worth I can't replicate this.)

**Comment by CCWRoy** [comment]
Ok, let me try to force my matplotlib from Anaconda 4.4.0 to use gtk 2 or Qt. I'm defending my thesis in a few days, so I try this after that :)

**Comment by timholy** [comment]
No hurry, I just wanted to make sure you knew you were not forgotten. I've been completely swamped myself the last couple of weeks.

**Comment by lewisl** [comment]
Possibly similar.  Julia segfaults for me if I do using PyPlot and using ImageView in the same file.  
When the code does a plot, then Julia segfaults (error 11) when trying to call Python.  The messages generated appear to come from Python rather than Julia.

Let me know what will help interpret.  I can certainly post the messages generated.

When I comment out #using ImageView then there is no problem.

**Comment by timholy** [comment]
Did you try the link posted above?

**Comment by lewisl** [comment]
I'll give it a shot after the holidays.  Tx.

**Comment by timholy** [comment]
Pretty sure https://github.com/JuliaImages/ImageView.jl/issues/128#issuecomment-338315409
